worker_processes 1;
pid @ROOT@/data/run/nginx.pid;
error_log @ROOT@/data/logs/nginx-error.log;
lock_file @ROOT@/data/run/nginx.lock;

events {
    worker_connections 128;
}

http {
    include @NGINX@/conf/mime.types;
    access_log off;
    client_max_body_size 25M;
    client_body_temp_path @ROOT@/data/tmp/nginx;
    fastcgi_temp_path @ROOT@/data/tmp/nginx;
    proxy_temp_path @ROOT@/data/tmp/nginx;
    uwsgi_temp_path @ROOT@/data/tmp/nginx;
    scgi_temp_path @ROOT@/data/tmp/nginx;

    server {
        listen @WEBIP@:@WEBPORT@;
        server_name localhost;
        root @ROOT@/web;
        index index.php;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            fastcgi_pass unix:@ROOT@/data/run/php-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
