[global]
error_log = @ROOT@/data/logs/php-fpm.log
pid = @ROOT@/data/run/php-fpm.pid
daemonize = yes

[www]
user = @USER@
group = @GROUP@
listen = @ROOT@/data/run/php-fpm.sock
listen.owner = @USER@
listen.group = @GROUP@
listen.mode = 0666
pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
chdir = @ROOT@/web
catch_workers_output = yes

php_value[display_errors] = On
php_admin_value[error_reporting] = E_ALL
php_admin_value[session.cookie_httponly] = 0
php_admin_value[session.cookie_secure] = 0
php_admin_value[session.save_path] = @ROOT@/data/sessions
php_admin_value[upload_tmp_dir] = @ROOT@/data/tmp
php_admin_value[upload_max_filesize] = 20M
php_admin_value[post_max_size] = 25M
